// Code generated by protoc-gen-easymicro-client. DO NOT EDIT.
package redisproxy

import (
	"sync"

	easymicrogrpc "github.com/995933447/easymicro/grpc"
	"context"
	"google.golang.org/grpc"
)

const (
	EasymicroGRPCSchema    = "redisproxy"
	EasymicroDiscoveryName = "redisproxy"
)

const EasymicroGRPCPbServiceNameRedisProxy = "redisproxy.RedisProxy"

var RedisProxyDefault = &RedisProxy{}

func RedisProxyGRPC() *RedisProxy {
	return RedisProxyDefault
}

func NewRedisProxyGRPC(dialOpts ...grpc.DialOption) *RedisProxy {
	return &RedisProxy{
		dialOpts: dialOpts,
	}
}

type RedisProxy struct {
	c        RedisProxyClient
	conn     *grpc.ClientConn
	once     sync.Once
	mu       sync.RWMutex
	dialOpts []grpc.DialOption
}

func (s *RedisProxy) Close() error {
	err := s.conn.Close()
	if err != nil {
		return err
	}
	return nil
}

func (s *RedisProxy) prepareConn() error {
	var err error
	s.once.Do(func() {
		var conn *grpc.ClientConn
		opts := s.dialOpts
		if opts == nil {
			opts = easymicrogrpc.BuildServiceDialOpts(EasymicroGRPCPbServiceNameRedisProxy)
		}
		conn, err = grpc.NewClient(EasymicroGRPCSchema+":///"+EasymicroGRPCPbServiceNameRedisProxy, opts...)
		if err != nil {
			return
		}
		s.conn = conn
		s.c = NewRedisProxyClient(conn)
	})
	if err != nil {
		return err
	}
	return nil
}

func (s *RedisProxy) Do(ctx context.Context, in *DoReq, opts ...grpc.CallOption) (*DoResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.Do(ctx, in, opts...)
}
