// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.24.2
// source: redisproxy.proto

package redisproxy

import (
	_ "github.com/995933447/mconfigcenter/ext"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrCode int32

const (
	ErrCode_ErrCodeNil      ErrCode = 0
	ErrCode_ErrCodeRedisNil ErrCode = 3001
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0:    "ErrCodeNil",
		3001: "ErrCodeRedisNil",
	}
	ErrCode_value = map[string]int32{
		"ErrCodeNil":      0,
		"ErrCodeRedisNil": 3001,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_redisproxy_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_redisproxy_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_redisproxy_proto_rawDescGZIP(), []int{0}
}

type Type int32

const (
	Type_TypeNil        Type = 0
	Type_TypeString     Type = 1
	Type_TypeInt64      Type = 2
	Type_TypeUint64     Type = 3
	Type_TypeFloat64    Type = 4
	Type_TypeBytes      Type = 5
	Type_TypeBytesArray Type = 6
	Type_TypeAnyArray   Type = 7
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "TypeNil",
		1: "TypeString",
		2: "TypeInt64",
		3: "TypeUint64",
		4: "TypeFloat64",
		5: "TypeBytes",
		6: "TypeBytesArray",
		7: "TypeAnyArray",
	}
	Type_value = map[string]int32{
		"TypeNil":        0,
		"TypeString":     1,
		"TypeInt64":      2,
		"TypeUint64":     3,
		"TypeFloat64":    4,
		"TypeBytes":      5,
		"TypeBytesArray": 6,
		"TypeAnyArray":   7,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_redisproxy_proto_enumTypes[1].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_redisproxy_proto_enumTypes[1]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_redisproxy_proto_rawDescGZIP(), []int{1}
}

type DoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrValue      string                 `protobuf:"bytes,1,opt,name=str_value,json=strValue,proto3" json:"str_value,omitempty"`
	BytesValue    []byte                 `protobuf:"bytes,2,opt,name=bytes_value,json=bytesValue,proto3" json:"bytes_value,omitempty"`
	Int64Value    int64                  `protobuf:"varint,3,opt,name=int64_value,json=int64Value,proto3" json:"int64_value,omitempty"`
	AnyArrayValue []*Any                 `protobuf:"bytes,4,rep,name=any_array_value,json=anyArrayValue,proto3" json:"any_array_value,omitempty"`
	Type          int32                  `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoResp) Reset() {
	*x = DoResp{}
	mi := &file_redisproxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoResp) ProtoMessage() {}

func (x *DoResp) ProtoReflect() protoreflect.Message {
	mi := &file_redisproxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoResp.ProtoReflect.Descriptor instead.
func (*DoResp) Descriptor() ([]byte, []int) {
	return file_redisproxy_proto_rawDescGZIP(), []int{0}
}

func (x *DoResp) GetStrValue() string {
	if x != nil {
		return x.StrValue
	}
	return ""
}

func (x *DoResp) GetBytesValue() []byte {
	if x != nil {
		return x.BytesValue
	}
	return nil
}

func (x *DoResp) GetInt64Value() int64 {
	if x != nil {
		return x.Int64Value
	}
	return 0
}

func (x *DoResp) GetAnyArrayValue() []*Any {
	if x != nil {
		return x.AnyArrayValue
	}
	return nil
}

func (x *DoResp) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type DoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Key           *RedisKey              `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Args          []*Any                 `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Ttl           int64                  `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	IsAsync       bool                   `protobuf:"varint,5,opt,name=is_async,json=isAsync,proto3" json:"is_async,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoReq) Reset() {
	*x = DoReq{}
	mi := &file_redisproxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoReq) ProtoMessage() {}

func (x *DoReq) ProtoReflect() protoreflect.Message {
	mi := &file_redisproxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoReq.ProtoReflect.Descriptor instead.
func (*DoReq) Descriptor() ([]byte, []int) {
	return file_redisproxy_proto_rawDescGZIP(), []int{1}
}

func (x *DoReq) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *DoReq) GetKey() *RedisKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *DoReq) GetArgs() []*Any {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *DoReq) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *DoReq) GetIsAsync() bool {
	if x != nil {
		return x.IsAsync
	}
	return false
}

type RedisKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conn          string                 `protobuf:"bytes,1,opt,name=conn,proto3" json:"conn,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedisKey) Reset() {
	*x = RedisKey{}
	mi := &file_redisproxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedisKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisKey) ProtoMessage() {}

func (x *RedisKey) ProtoReflect() protoreflect.Message {
	mi := &file_redisproxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisKey.ProtoReflect.Descriptor instead.
func (*RedisKey) Descriptor() ([]byte, []int) {
	return file_redisproxy_proto_rawDescGZIP(), []int{2}
}

func (x *RedisKey) GetConn() string {
	if x != nil {
		return x.Conn
	}
	return ""
}

func (x *RedisKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type Any struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Type            int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	BytesValue      []byte                 `protobuf:"bytes,2,opt,name=bytes_value,json=bytesValue,proto3" json:"bytes_value,omitempty"`
	StrValue        string                 `protobuf:"bytes,3,opt,name=str_value,json=strValue,proto3" json:"str_value,omitempty"`
	Int64Value      int64                  `protobuf:"varint,4,opt,name=int64_value,json=int64Value,proto3" json:"int64_value,omitempty"`
	Uint64Value     uint64                 `protobuf:"varint,5,opt,name=uint64_value,json=uint64Value,proto3" json:"uint64_value,omitempty"`
	FloatValue      float64                `protobuf:"fixed64,6,opt,name=float_value,json=floatValue,proto3" json:"float_value,omitempty"`
	BytesArrayValue [][]byte               `protobuf:"bytes,7,rep,name=bytes_array_value,json=bytesArrayValue,proto3" json:"bytes_array_value,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Any) Reset() {
	*x = Any{}
	mi := &file_redisproxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Any) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Any) ProtoMessage() {}

func (x *Any) ProtoReflect() protoreflect.Message {
	mi := &file_redisproxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Any.ProtoReflect.Descriptor instead.
func (*Any) Descriptor() ([]byte, []int) {
	return file_redisproxy_proto_rawDescGZIP(), []int{3}
}

func (x *Any) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Any) GetBytesValue() []byte {
	if x != nil {
		return x.BytesValue
	}
	return nil
}

func (x *Any) GetStrValue() string {
	if x != nil {
		return x.StrValue
	}
	return ""
}

func (x *Any) GetInt64Value() int64 {
	if x != nil {
		return x.Int64Value
	}
	return 0
}

func (x *Any) GetUint64Value() uint64 {
	if x != nil {
		return x.Uint64Value
	}
	return 0
}

func (x *Any) GetFloatValue() float64 {
	if x != nil {
		return x.FloatValue
	}
	return 0
}

func (x *Any) GetBytesArrayValue() [][]byte {
	if x != nil {
		return x.BytesArrayValue
	}
	return nil
}

var File_redisproxy_proto protoreflect.FileDescriptor

const file_redisproxy_proto_rawDesc = "" +
	"\n" +
	"\x10redisproxy.proto\x12\n" +
	"redisproxy\x1a\text.proto\"\xb4\x01\n" +
	"\x06DoResp\x12\x1b\n" +
	"\tstr_value\x18\x01 \x01(\tR\bstrValue\x12\x1f\n" +
	"\vbytes_value\x18\x02 \x01(\fR\n" +
	"bytesValue\x12\x1f\n" +
	"\vint64_value\x18\x03 \x01(\x03R\n" +
	"int64Value\x127\n" +
	"\x0fany_array_value\x18\x04 \x03(\v2\x0f.redisproxy.AnyR\ranyArrayValue\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x05R\x04type\"\x9b\x01\n" +
	"\x05DoReq\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12&\n" +
	"\x03key\x18\x02 \x01(\v2\x14.redisproxy.RedisKeyR\x03key\x12#\n" +
	"\x04args\x18\x03 \x03(\v2\x0f.redisproxy.AnyR\x04args\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\x03R\x03ttl\x12\x19\n" +
	"\bis_async\x18\x05 \x01(\bR\aisAsync\"0\n" +
	"\bRedisKey\x12\x12\n" +
	"\x04conn\x18\x01 \x01(\tR\x04conn\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\xe8\x01\n" +
	"\x03Any\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x1f\n" +
	"\vbytes_value\x18\x02 \x01(\fR\n" +
	"bytesValue\x12\x1b\n" +
	"\tstr_value\x18\x03 \x01(\tR\bstrValue\x12\x1f\n" +
	"\vint64_value\x18\x04 \x01(\x03R\n" +
	"int64Value\x12!\n" +
	"\fuint64_value\x18\x05 \x01(\x04R\vuint64Value\x12\x1f\n" +
	"\vfloat_value\x18\x06 \x01(\x01R\n" +
	"floatValue\x12*\n" +
	"\x11bytes_array_value\x18\a \x03(\fR\x0fbytesArrayValue*/\n" +
	"\aErrCode\x12\x0e\n" +
	"\n" +
	"ErrCodeNil\x10\x00\x12\x14\n" +
	"\x0fErrCodeRedisNil\x10\xb9\x17*\x88\x01\n" +
	"\x04Type\x12\v\n" +
	"\aTypeNil\x10\x00\x12\x0e\n" +
	"\n" +
	"TypeString\x10\x01\x12\r\n" +
	"\tTypeInt64\x10\x02\x12\x0e\n" +
	"\n" +
	"TypeUint64\x10\x03\x12\x0f\n" +
	"\vTypeFloat64\x10\x04\x12\r\n" +
	"\tTypeBytes\x10\x05\x12\x12\n" +
	"\x0eTypeBytesArray\x10\x06\x12\x10\n" +
	"\fTypeAnyArray\x10\a29\n" +
	"\n" +
	"RedisProxy\x12+\n" +
	"\x02Do\x12\x11.redisproxy.DoReq\x1a\x12.redisproxy.DoRespBH\x8a\x9d \x18Z\n" +
	"redisproxyb\n" +
	"redisproxyZ*github.com/995933447/redisproxy/redisproxyb\x06proto3"

var (
	file_redisproxy_proto_rawDescOnce sync.Once
	file_redisproxy_proto_rawDescData []byte
)

func file_redisproxy_proto_rawDescGZIP() []byte {
	file_redisproxy_proto_rawDescOnce.Do(func() {
		file_redisproxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_redisproxy_proto_rawDesc), len(file_redisproxy_proto_rawDesc)))
	})
	return file_redisproxy_proto_rawDescData
}

var file_redisproxy_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_redisproxy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_redisproxy_proto_goTypes = []any{
	(ErrCode)(0),     // 0: redisproxy.ErrCode
	(Type)(0),        // 1: redisproxy.Type
	(*DoResp)(nil),   // 2: redisproxy.DoResp
	(*DoReq)(nil),    // 3: redisproxy.DoReq
	(*RedisKey)(nil), // 4: redisproxy.RedisKey
	(*Any)(nil),      // 5: redisproxy.Any
}
var file_redisproxy_proto_depIdxs = []int32{
	5, // 0: redisproxy.DoResp.any_array_value:type_name -> redisproxy.Any
	4, // 1: redisproxy.DoReq.key:type_name -> redisproxy.RedisKey
	5, // 2: redisproxy.DoReq.args:type_name -> redisproxy.Any
	3, // 3: redisproxy.RedisProxy.Do:input_type -> redisproxy.DoReq
	2, // 4: redisproxy.RedisProxy.Do:output_type -> redisproxy.DoResp
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_redisproxy_proto_init() }
func file_redisproxy_proto_init() {
	if File_redisproxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_redisproxy_proto_rawDesc), len(file_redisproxy_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_redisproxy_proto_goTypes,
		DependencyIndexes: file_redisproxy_proto_depIdxs,
		EnumInfos:         file_redisproxy_proto_enumTypes,
		MessageInfos:      file_redisproxy_proto_msgTypes,
	}.Build()
	File_redisproxy_proto = out.File
	file_redisproxy_proto_goTypes = nil
	file_redisproxy_proto_depIdxs = nil
}
