// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.2
// source: redisproxy.proto

package redisproxy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RedisProxy_Do_FullMethodName = "/redisproxy.RedisProxy/Do"
)

// RedisProxyClient is the client API for RedisProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RedisProxyClient interface {
	Do(ctx context.Context, in *DoReq, opts ...grpc.CallOption) (*DoResp, error)
}

type redisProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewRedisProxyClient(cc grpc.ClientConnInterface) RedisProxyClient {
	return &redisProxyClient{cc}
}

func (c *redisProxyClient) Do(ctx context.Context, in *DoReq, opts ...grpc.CallOption) (*DoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DoResp)
	err := c.cc.Invoke(ctx, RedisProxy_Do_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RedisProxyServer is the server API for RedisProxy service.
// All implementations must embed UnimplementedRedisProxyServer
// for forward compatibility.
type RedisProxyServer interface {
	Do(context.Context, *DoReq) (*DoResp, error)
	mustEmbedUnimplementedRedisProxyServer()
}

// UnimplementedRedisProxyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRedisProxyServer struct{}

func (UnimplementedRedisProxyServer) Do(context.Context, *DoReq) (*DoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Do not implemented")
}
func (UnimplementedRedisProxyServer) mustEmbedUnimplementedRedisProxyServer() {}
func (UnimplementedRedisProxyServer) testEmbeddedByValue()                    {}

// UnsafeRedisProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RedisProxyServer will
// result in compilation errors.
type UnsafeRedisProxyServer interface {
	mustEmbedUnimplementedRedisProxyServer()
}

func RegisterRedisProxyServer(s grpc.ServiceRegistrar, srv RedisProxyServer) {
	// If the following call pancis, it indicates UnimplementedRedisProxyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RedisProxy_ServiceDesc, srv)
}

func _RedisProxy_Do_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisProxyServer).Do(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisProxy_Do_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisProxyServer).Do(ctx, req.(*DoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RedisProxy_ServiceDesc is the grpc.ServiceDesc for RedisProxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RedisProxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "redisproxy.RedisProxy",
	HandlerType: (*RedisProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Do",
			Handler:    _RedisProxy_Do_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "redisproxy.proto",
}
