// Code generated by protoc-gen-easymicro-server. DO NOT EDIT.
package boot

import (
	"github.com/995933447/easymicro/nats"
	"github.com/995933447/redisproxy/redisproxy"
	"github.com/995933447/redisproxy/redisproxyserver/handler"
)

func RegisterNatsRPCRoutes() error {
	var err error

	err = nats.HandleLikeGRPC(redisproxy.EasymicroGRPCPbServiceNameRedisProxy, "Do", handler.RedisProxyHandler.Do, func() *redisproxy.DoReq {
		return &redisproxy.DoReq{}
	})
	if err != nil {
		return err
	}

	return nil
}
