// Code generated by protoc-gen-easymicro-server. DO NOT EDIT.
package boot

import (
	"github.com/995933447/easymicro/node"
)

var RPCPort = 0

func InitNode(nodeName string) error {
	if err := node.SetName(nodeName); err != nil {
		return err
	}

	if RPCPort == 0 {
		_, err := node.GetOrAutoSetPort()
		if err != nil {
			return err
		}
		return nil
	}

	return node.SetPort(RPCPort)
}
