// Code generated by protoc-gen-easymicro-server. DO NOT EDIT.
package boot

import (
	"github.com/995933447/redisproxy/redisproxy"
	"github.com/995933447/redisproxy/redisproxyserver/handler"
	"google.golang.org/grpc"
)

var ServiceNames = []string{
	redisproxy.EasymicroGRPCPbServiceNameRedisProxy,
}

var RegisterServiceServers = func(server *grpc.Server) error {
	redisproxy.RegisterRedisProxyServer(server, handler.RedisProxyHandler)
	return nil
}
